version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FAL_API_KEY=${FAL_API_KEY}
      - GIT_URL=${GIT_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
